# -*- coding: utf-8 -*-
"""pizzadeliveries.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12-vAexEbX4fnwcp65t9ffKyXf-B60nrT
"""

print("Bienvenue dans Python Pizza Deliveries!")
prix=0
taille=input("quelle est la taille de pizza que vous souhaitez acheter? (petite_pizza/moyenne_pizza/grande_pizza):")
if taille=="petite_pizza":
  prix +=15
elif taille=="moyenne_pizza":
  prix +=20
elif taille=="grande_pizza":
  prix +=25
add_pepperoni=input("Souhaitez-vous ajouter du pepperoni sur votre pizza? (oui/non)")
if add_pepperoni=="oui":
  if taille=="petite_pizza":
    prix +=2
  else:
   prix +=3
extra_cheese=input("Souhaitez-vous avoir du fromage supplémentaire sur votre pizza? (oui/non)")
if extra_cheese=="oui":
  prix +=1


print(f"Votre facture finale est de {prix} $.")